### ISSUE TITLE
I like this but could this be expanded as some kind of page state manager?

### ISSUE THREAD

**Issue by DOTang** [vegasje/form-helper#1]
I like the general style of this thing and I realize it is strictly for form validation, and what I am proposing is more than that but I wonder if it couldn't follow the same design and include validation in there.

Things the state manager would need:

1.  Ability to nest containers for complex objects in the fields area (Eg a collection of addresses, with fields for street, city, state, zip, with the ability to validate the collection to make sure there are no duplicates).
2. Ability to store and validate data not associated with form elements but would be stored in the UI.
3. Ability to getState of individual fields which could potentially be used within the validate method to validate data that is not associated with any UI elements but only exist in javascript.

Some psuedo JS modification I could see might be something like this:

```javascript
var pageState = $('.page-container').PageState(
	validationOptions: validationOptions,
	model: {
		{
			firstName, $(".first-name").val(), {
			validate: [FormHelper.validations.minLength(4)]
			}
		},
		{
			lastName, $(".last-name").val(), {
				validate: [FormHelper.validations.minLength(4)]
			}
		},
		{
			addresses[], $(".address-item") /*container for a mustache template though irrelevant*/, {
				fields: {
					{
						street, $("input[name^=\"news\"]").val(), {
							validate: [FormHelper.validations.minLength(5)]
						}
					},
						{
						city, $("input[name^=\"city\"]"), {
							validate: [FormHelper.validations.minLength(2)]
						}
					},
					//etc
				},
				validate: [
					function(value) {
						value.GetState().each(//some code to ensure no addresses are identical) (?? maybe ??) 
					}
				]
				}
			}
		},
		{
			currentEmotions[], function($(".selected-emotions-template")){
				var emotions[];
				$(this).find(".selected-emotion-item").each(function(itemContainer){
					var emotionId = $(itemContainer).find("span.emotion-id").text();
					var emotionName = $(itemContainer).find("span.emotion-name").text();
					emotions.push({id: emotionId, name: emotionName});
				})
			}, {
				validate: [
					function(value){
						return value.length > 0;
					}
				]
			}

		}
	}
});


```

```html
<div id="page-container">
	First Name: <input type="text" class="first-name" name="first-name"  />
	Last Name: <input type="text" class="last-name" name="last-name"  />
	Addresses:
	<div class="addresses-template">
		Address 1
		<div class="address-item">
			<input type="text" class="street" name="street" />
			<input type="text" class="city" name="city" />
		</div>
		Address 2
		<div class="address-item">
			<input type="text" class="street" name="street" />
			<input type="text" class="city" name="city" />
		</div>
	</div>
	Current Emotions:
	<div class="emotions">
		<select class="available-emotions" name="available-emotions">
			<options value="0">-- Select an emotion --</options>
			<options value="1">Happy</options>
			<options value="2">Sad</options>
			<options value="3">Angry</options>
		</select>
		<button type="button">+ Add Emotion</button>
		<div class="selected-emotions-template">
			<div class="selected-emotion-item">
				<span class="emotion-name">Happy</span><span style="display: none;" class="emotion-id">1</span><button type="button">Remove</button>
			</div>
			<div class="selected-emotion-item">
				<span class="emotion-name">Angry</span><span style="display: none;" class="emotion-id">3</span><button type="button">Remove</button>
			</div>
		</div>
	</div>
</div>
```

After supplying the fieldName, you could supply a selector or function to get that value, it's very rough and probably not even valid javascript, used a plain text editor to write it. Though not sure how far eep you could do, perhaps currentEmotions could have nested id and name fields instead of what I put there?

**Comment by vegasje** [comment]
What does the `validationOptions` property represent?

**Comment by DOTang** [comment]
Oh just your onPass an OnFail methods you supplied at the top level of the form helper object.

One problem I see in that I am trying to add full page state manager to this is how do you support non UI backed properties? I'm not even sure if it makes sense to do so, because even in my example all my properties are populated by data acquired from the UI. So storing something not used in the UI at all but only javascript seems like it wouldn't work in this state manager.

**Comment by vegasje** [comment]
I'm putting some properly-formatted JS below to see if I understand the concept here.  Please correct it if these changes do not mesh with your concept.  At this point I am not trying to come up with a good implementation, simply trying to correct the syntax.

```javascript
var pageState = $('.page-container').PageState({
	validationOptions: validationOptions,
	model: {
		firstName: {
			getState: $(".first-name").val, // This should be a function reference rather than a hard value, since it would need to be called at a point in the future.
			validate: [FormHelper.validations.minLength(4)]
		},
		lastName: {
			getState: $(".last-name").val,
			validate: [FormHelper.validations.minLength(4)]
		},
		'addresses[]': {
			fields: {
				street: {
					getState: $("input[name^=\"news\"]").val,
					validate: [FormHelper.validations.minLength(5)]
				},
				city: {
					getState: $("input[name^=\"city\"]").val,
					validate: [FormHelper.validations.minLength(2)]
				},
				//etc
			},
			validate: [
				function(value) {
					value.GetState().each(//some code to ensure no addresses are identical) (?? maybe ??)
				}
			]
		},
		'currentEmotions[]': {
			getState: function($(".selected-emotions-template")) {
				var emotions = [];
				$(this).find(".selected-emotion-item").each(function(itemContainer) {
					var emotionId = $(itemContainer).find("span.emotion-id").text();
					var emotionName = $(itemContainer).find("span.emotion-name").text();
					emotions.push({id: emotionId, name: emotionName});
				});
				return emotions;
			},
			validate: [
				function(value) {
					return value.length > 0;
				}
			]
		}
	}
});
```

**Comment by DOTang** [comment]
Yes that looks to be correct.

**Comment by vegasje** [comment]
Ok.  Here is my crack at what a configuration could look like.  I believe it still achieves your objectives, and simply extends the existing FormHelper configuration.

```html
<div id="page-container">
	First Name: <input type="text" class="first-name" name="first-name"  />
	Last Name: <input type="text" name="lastName"  />

	Addresses:
	<div class="addresses">
		Address 1
		<div class="address-item">
			<input type="text" class="street" name="street-1" />
			<input type="text" class="city" name="city-1" />
		</div>

		Address 2
		<div class="address-item">
			<input type="text" class="street" name="street-2" />
			<input type="text" class="city" name="city-2" />
		</div>
	</div>

	Current Emotions:
	<div class="emotions">
		<select class="available-emotions" name="available-emotions">
			<option value="0">-- Select an emotion --</option>
			<option value="1">Happy</option>
			<option value="2">Sad</option>
			<option value="3">Angry</option>
		</select>

		<button type="button">+ Add Emotion</button>

		<div class="selected-emotions">
			<div class="selected-emotion-item">
				<span class="emotion-name">Happy</span><span style="display: none;" class="emotion-id">1</span><button type="button">Remove</button>
			</div>

			<div class="selected-emotion-item">
				<span class="emotion-name">Angry</span><span style="display: none;" class="emotion-id">3</span><button type="button">Remove</button>
			</div>
		</div>
	</div>

	Weird Stuff:
	<input class="weird" name="weird-1" />
	<input class="stuff" name="stuff-1" />
	<input class="weird" name="weird-2" />
	<input class="stuff" name="stuff-2" />
</div>
```

```javascript
var pageHelper = $('.page-container').FormHelper({
	// The global `onFail` method doesn't change from current implementation.
	onFail: function() { ... },

	// The global `onPass` method doesn't change from current implementation.
	onPass: function() { ... },

	fields: {
		// Selector-only configuration.
		firstName: {
			selector: '.first-name',
			validate: [FormHelper.validations.minLength(4)]
		},

		// Form field name configuration (default).
		lastName: {
			// Assuming `lastName` is also the name of the form field, then we don't need to define state.
			// This would allow forms currently configured with FormHelper to continue working.
			validate: [FormHelper.validations.minLength(4)]
		},

		// Parent selector with child selectors configuration.
		addresses: {
			selector: '.address-item',
			fields: {
				street: {
					selector: '.street',
					validate: [FormHelper.validations.minLength(5)]
				},

				city: {
					selector: '.city',
					validate: [FormHelper.validations.minLength(2)]
				}
			},
			validate: [
				function(value) {
					// `value` is an array of objects, and
					// each object contains a `street` and a `city`.
				}
			]
		},

		// Parent selector with child states configuration.
		emotions: {
			selector: '.selected-emotions',
			fields: {
				id: {
					state: function($parent) {
						// In this context, `$parent` represents the `.selected-emotions` element.
						return $('.emotion-id', $parent).text();
					}
				},
				name: {
					state: function($parent) {
						return $('.emotion-name', $parent).text();
					}
				}
			},
			validate: [
				function(value) {
					// `value` is the array of emotions built in the `state` function.
					return value.length > 0;
				}
			]
		},

		// Parent state configuration that builds the full object.
		weirdStuff: {
			state: function($parent) {
				// In this context, `$parent` represents the `.page-container` element.
				var weirds = $('.weird').map(function() {
					return $(this).val();
				}).get();

				var stuffs = $('.stuff').map(function() {
					return $(this).val();
				});

				var weirdStuffs = [];

				for (var i = 0; i < weirds.length; i++) {
					weirdStuffs.push({
						weird: weirds[i],
						stuff: stuffs[i]
					});
				}

				return weirdStuffs;
			}
		}
	}
});
```

In this design, there are mulitple ways in which fields can be configured.  I'll be the first to say that it seems confusing.

1. **Form field name configuration (default).**  This configuration is what FormHelper uses currently.  The key of the field in the configuration array matches the name of the form field element.  In the above example, `lastName` uses this configuration.
2. **Selector-only configuration.**  This configuration uses a selector to fetch the value of the field rather than relying on the name of the form field element.  In the above example, `firstName` uses this configuration.
3. **Parent selector with child selectors configuration.**  This configuration uses a selector on the parents to determine groups of fields, and the selectors on the child fields are used to populate the individual values for each element of the array.  Child selectors are relative to their parent selectors.  In the above example, `addresses` uses this configuration.
4. **Parent selector with child states configuration.**  This configuration uses a selector on the parents to determine groups of fields, and the children have `state` functions that fetch their values in custom ways.  The `$parent` parameter passed to the `state` function is a jQuery object that represents the parent element.  This allows the `state` function to issue jQuery selectors relative to the parent.  In the above example, `emotions` uses this configuration.
5. **Parent state configuration that builds the full object.**  This is the most custom configuration, and it allows a key to build its child data however it sees fit.  A configuration that uses state would never have any fields configured underneath it, as it is responsible for building the entire state of itself.  In the above example, `weirdStuff` uses this configuration.

The biggest issue that I see with this implementation (aside from the complexity) is that it differs significantly from how FormHelper currently works with respect to the `currentState()` method:

https://github.com/vegasje/form-helper/blob/master/lib/form-helper.js#L154-L173

Currently this method grabs all form elements and uses their name to determine how the values get keyed in an object.  This new configuration takes a totally different approach--it expects all data to be defined in the configuration.  I would assume your intention was that any field that does **not** appear in the configuration would not be included when calling `currentState()`.

If that is true, that's a relatively tough cookie to swallow, as it mandates that all fields be configured even if they don't need any kind of validation.  This makes it much clunkier to use for large forms of mostly unvalidated data (preventing something like `$('.simple-form').FormHelper().currentState();` from working).

**Comment by DOTang** [comment]
Looks very good, yes I do agree it might be a tad confusing having all these allowable configurations, but I could think of examples where I would use maybe all of them, if everything has a default functionality and you can just provide more properties like selector/state if you need that customization, maybe it's not so bad. Can you think of anyway of reducing the ways to customize a field while still allowing the same or near same flexibility?

Interesting point you make about get current state, in my pages I do all my "form" submits via ajax so I don't have any form tags, but I don't see why that default functionality wouldn't be provided, or perhaps a boolean value to provide that? Also another property that is an array to maybe ignore certain fields by selector or name? Like in the example above, the emotions dropdown could be ignored, I don't care about that.

**Comment by vegasje** [comment]
At this time I can't think of any ways of making this as flexible with less configuration.  But I'm open to suggestion.

I do believe that, even in the current FormHelper, an ignore list would be beneficial.  However this should be a separate Issue.

After this conversation, I believe these modifications could be beneficial to a wide range of developers.  I will work on these improvements.  I will also create two additional issues:  One for an ignore list, and a second for creating one or more example files to showcase and test these different configuration options.

**Comment by vegasje** [comment]
Selector-based state retrieval added in https://github.com/vegasje/form-helper/commit/1141d1cffa78e26fcd758f95a39abd11341819b7

**Comment by vegasje** [comment]
Selector-based validation added in https://github.com/vegasje/form-helper/commit/9e09fe4a9f3827ad7afba7b87c3ed3c30f8baaa4

**Comment by vegasje** [comment]
Custom state support added for both validation and state in https://github.com/vegasje/form-helper/commit/2f3af1227229dddbd5f8a4e69ca71ac1dbd7efad

**Comment by vegasje** [comment]
I see a potential issue with the custom `state` option when configuring the FormHelper.

We are able to use the `state` definition as specced above for correctly retrieving form state and validating that state.  This works well.

However, when validation passes or fails, we don't really have a good reference object to pass to the `onPass`/`onFail` functions.

```javascript
...
		emotions: {
			selector: '.selected-emotions',
			fields: {
				id: {
					state: function($parent) {
						// In this context, `$parent` represents the `.selected-emotions` element.
						return $('.emotion-id', $parent).text();
					},
					validate: [FormHelper.validations.notEmpty()],
					onFail: function() {
						// Typically we would do something like $(this).addClass('error');
						// What do I do here?
					},
					onPass: function() {
						// Typically we would do something like $(this).removeClass('error');
						// What do I do here?
					}
				},
				name: {
					state: function($parent) {
						return $('.emotion-name', $parent).text();
					}
				}
			},
			validate: [
				function(value) {
					// `value` is the array of emotions built in the `state` function.
					return value.length > 0;
				}
			]
		},
...
```

Using this snippet from the example above, I have added a validation handler to emotion ids.  Imagine that one of the emotion ids is empty, and therefore not valid.  The `onFail` function receives a jQuery object, and that object is typically used to apply a class indicating failure to the user.  In this example, the most specific jQuery object we would have to pass into that `onFail` function would be `$('.selected-emotions')`, which is the container for all the emotions.

Given that jQuery object, the best a developer could do would be to apply some failure indicator to the entire `.selected-emotions` container, which isn't all that helpful, or to use some very custom logic inside the `onFail` function to try and hunt down the emotion that failed validation.  That would be labor intensive, and it would be great if we could avoid requiring that of the developer.

**Comment by vegasje** [comment]
After discussion, I think the only reasonable way to achieve this would be to require a selector even when using custom state retrieval.

The example above becomes:

```javascript
...
		emotions: {
			selector: '.selected-emotions',
			fields: {
				id: {
					selector: '.emotion-id',
					state: function($elem) {
						// In this context, `$elem` represents the element retrieved from the selector, in the context of the parent.
						return $elem.text();
					},
					validate: [FormHelper.validations.notEmpty()],
					onFail: function() {
						// $(this) now represents the element from the selector.
					},
					onPass: function() {
						// $(this) now represents the element from the selector.
					}
				},
				name: {
					selector: '.emotion-name',
					state: function($elem) {
						return $elem.text();
					}
				}
			},
			validate: [
				function(value) {
					// `value` is the array of emotions built in the `state` function.
					return value.length > 0;
				}
			]
		},
...
```

Since the element retrieved from the selector is now being passed into the state function, this actually ends up being close to the same amount of configuration as before, even though it is a little clumsier.

**Comment by vegasje** [comment]
Nested state added in https://github.com/vegasje/form-helper/commit/4e6621412d368ac1bae10bc09f385643d0f186a8

This completes the issue.
