### ISSUE TITLE
Allow validation and state on a per field basis.

### ISSUE THREAD

**Issue by DOTang** [vegasje/form-helper#4]
I have my current validation plugin go form field by form field and update in real time as the user moves through the form, applying pass/fail styles on each field as they go. Currently that is impossible with this library since all validations must be applied at once.

Same with getting state. As simple example would be after a user selects a specific value from a dropdown, and I load more detailed information about whatever was selected. Sure, this could easily be done with a jquery change on the dropdown, but as the examples become more complicated, doing it "myself" in jquery becomes repetitive. If I am already declaring how to get the state of a field in formHelper, why would I want to write more code elsewhere to also get it. when how to get it is already configured in form Helper.

**Comment by vegasje** [comment]
Let's think about how this would be accomplished.  Take the following example:

```javascript
...
notebook: {
	selector: '.notebook',
	fields: {
		heading: {
			selector: '.heading',
			state: function($elem) {
				return $elem.text();
			},
			validate: [FormHelper.validations.minLength(5)]
		},
		notes: {
			selector: '.notes',
			state: function($elem) {
				return $elem.children('span').map(function() {
					var $this = $(this);
					
					return {
						id: $this.attr('data-id'),
						note: $this.text()
					};
				}).get();
			},
			validate: [FormHelper.validations.notEmpty()]
		}
	}
},
...
```

Currently calling the `validate` method looks like: `helper.validate()`.  Let's say you wanted to only validate the notebook heading.  What would the call to `validate` look like?  You can assume you're able to retrieve the currently configured FormHelper settings by calling `helper.settings`.

**Comment by vegasje** [comment]
I will not be adding single-field state retrieval, but single-field validation has been added in https://github.com/vegasje/form-helper/commit/cf4660032ebc58073229c424f2860213bfa07060.
