### ISSUE TITLE
state returns two properties per field if using selector and name and id match

### ISSUE THREAD

**Issue by DOTang** [vegasje/form-helper#6]
Example:
```

<input id="overviewName" type="text" class="form-control k-textbox" placeholder="Enter name" style="width: 50%; min-width: 300px;" value="@Model.OverviewWizardPage.Name" />
<input id="overviewRenewalFrequency" name="overviewRenewalFrequency" type="number" class="form-control k-textbox" placeholder="Enter months" style="width: 20%; min-width: 200px;" value="@Model.OverviewWizardPage.RenewalFrequencyMonths" />
                       
```

JS:
```
fields: {
                    Name: {
                        selector: "#overviewName",
                        validate: [FormHelper.validations.minLength(4)]
                    },
                    RenewalFrequency: {
                        selector: "#overviewRenewalFrequency",
                        validate: [FormHelper.validations.isNumeric()]
                    },
```

Output of current state:
```
Name: "Registration"
RenewalFrequency: "60"
overviewRenewalFrequency:"60"
```

If I remove the name property (as seen with overviewName), there is no duplicate property. This seems like a bug since I may want to still have a name to support JS-less form entry, or input names are required for things like accessibility.

Interestingly enough, this still happens even if the ID and name don't match:
` <input id="overviewRenewalFrequency" name="overviewRenewalFrequency2" ...`
Produces:
```
Name:"Registration"
RenewalFrequency:"60"
overviewRenewalFrequency2:"60"
```
Which seems weird since the form helper options don't configure anything via field name or selector for "overviewRenewalFrequencey2"

**Comment by DOTang** [comment]
Upon looking at the code it seems like it's because explicitState is set to false so it's grabbing any inputs by name, but I'm not sure why the above wouldn't flag as explicit.

**Comment by vegasje** [comment]
As it stands, if you don't want FormHelper to automatically grab values by the field names, then you need to set `explicitState` to `true`.  This tells FormHelper that it doesn't need to automatically look for values, and that the config will be giving it all the instructions it needs.

The example HTML file includes an example with its usage.

The README doesn't have any information regarding `explicitState`, and that documentation should be added.

**Comment by vegasje** [comment]
This has been resolved.
